### ISSUE TITLE
A script in the extension 'Local Filesystem Links' is causing Firefox to slow down

### ISSUE THREAD

**Issue by adipose** [feinstaub/webextension_local_filesystem_links#120] opened 2018-02-09 17:16 UTC
We were using this at my company before webextensions, but with the new release, we constantly are warned of (and experience) major slowdowns in Firefox.  We've had to disable it for now.

**Comment by AWolf81** [comment] 2018-02-09 17:46
Thanks for reporting.

I've also noticed this (see issue #109) and I think it's related to the jquery update.

I'll check if I can do a quick-fix and disable jquery-observe for now if this is fixing the problem  (just dynamically added links won't get the folder icon).

I've also disabled the extension because it breaks some pages totally.

I'll add a comment here if I made some progress.

**Comment by adipose** [comment] 2018-02-09 18:26
Thanks!  Our application happens to not be dynamic, so that would work for us.  Perhaps you could make it an option to disable script/ajax created link scanning.  This would improve performance for those who don't need it, even once the bug is fixed.

**Comment by AWolf81** [comment] 2018-02-13 16:10
In 0.99.58 I've disabled the dynamic link feature. I think making an option for the link scanning is a good idea but it's probably better to have the performance so that there is no or small page delay detectable. (If I the delay is noticeable I'll add it as option.)

I need more time to find the cause of the page slow down - still not sure why it happens.

The new version should be soon available at Mozilla gallery. Not published yet but @feinstaub is checking the extension and upload it if everything is working as expected.

**Comment by feinstaub** [comment] 2018-02-15 11:50
see https://github.com/feinstaub/webextension_local_filesystem_links/issues/122

**Comment by AWolf81** [comment] 2019-08-07 00:03
Closing as we're tracking progress in the mentioned issue.

**Closed by AWolf81** 2019-08-07 00:03 UTC
