### ISSUE TITLE
possible cache issue 

### ISSUE THREAD

**Issue by montegue85** [feinstaub/webextension_local_filesystem_links#135] opened 2018-05-03 21:16 UTC
I have noticed that after a full day of use. I have to clear the cache on the firefox to get the extension to work again. 

Could this be a cache issues with the extension or another issues all together. Using this version for firefox : https://i.imgur.com/89mKpMH.png

**Comment by AWolf81** [comment] 2018-05-03 22:18
Thanks for reporting the issue.

- What happens when the extension stops working? 
  - Are the folder icons still visible? 
  - Links are not clickable anymore? 
- Simple reloading will not get the extension to work again?
- Which operating system do you use?

I have to reproduce the behaviour so I can fix the problem.

**Comment by Jennilein1991** [comment] 2018-05-07 08:26
Hello :)
i have a similar problem regarding caching in firefox. 
When a user has updated a file on a server (same name) and then is clicking on the local filesystem link for this file (on a Joomla website), the old file is opened.

**Comment by AWolf81** [comment] 2019-08-07 00:19
I couldn't reproduce the behavior so I'm closing this for now.

If it's still a problem we can reopen the issue but I'll need more details about the issue.

**Closed by AWolf81** 2019-08-07 00:19 UTC
