### ISSUE TITLE
Issue with UNC paths to html-file: first click opens once, second click opens twice...

### ISSUE THREAD

**Issue by benallemand** [feinstaub/webextension_local_filesystem_links#108] opened 2018-01-19 14:49 UTC
Hi,

I tried your plugin with your JSFiddle: http://jsfiddle.net/awolf2904/tefcs74q/
- Dynamic links added with javascript
- I added a UNC path (file://///<my_domain>/index.html)
- First time I click on "C: Link - 0"
- HTML page opens in a new Tab. I close it.
- I click again on "C: Link - 0"
- HTML page opens twice, in 2 new tabs.

If you are able to reproduce, can you please fix it ? I am using Firefox 57.0.4 (64-bit)

Thanks for your development !

Best Regards,
Ben

**Comment by AWolf81** [comment] 2018-01-20 10:46
Hi Ben:
Sorry, I can't reproduce your issue. It's working for me and you're doing it correctly with 5-slashes after the protocol colon. (4-slash support will be added in the next version of native app as mentioned in #106)
What's maybe a bit confusing in the fiddle is that it will add the link twice but that's intended to test asynchronous addition of the second link.

What do you mean by `<my_domain>`? It must be a network share in your local network. e.g. the dns name of your NAS or of a server or an IP address in your LAN.

**Comment by benallemand** [comment] 2018-01-21 16:53
Hi,
You can close the ticket I think: 
I just tried to reproduce on my personal PC, and it behaves in the same way... but after a refresh of the fiddle page, everything behaves correctly...

For your information, here is the behaviour just after installing plugin and native app:
Link created is:
file://///BEN-PC/Users/Ben/email_templates/template_1.html
I click once on the link => HTML file opens in 1 tab, I close it
I click a second time => HTML file opens in 2 tabs instead of expected 1 tab
I click a third time => HTML file opens in 3 tabs instead of expected 1 tab
I click a fourth time => HTML file opens in 3 tabs instead of expected 1 tab

It seems that this behaviour only occurs using HTML files.

Regards,
Ben

**Comment by AWolf81** [comment] 2018-01-21 22:15
I haven't tested to open html files before but this looks like a bug and I'd like to fix it.

**Points that I have to check:**
- [ ] First click seems to work as expected - opens a new tab with the html file but second click creates too many tabs - seems like the extension is re-added to the same page
- [ ] Is this only at jsfiddle? Or is this also in another test page?

**Comment by benallemand** [comment] 2018-01-22 08:53
FYI, I've tested it with JSFiddle, but also with a Confluence wiki page

**Comment by AWolf81** [comment] 2018-02-11 00:07
OK, this will be fixed in the next version. I've improved the content script handling.

**Closed** 2018-02-11 00:08 UTC
Labels: Bug
